### ISSUE TITLE
Loading sounds from remote HTTP paths

### ISSUE THREAD

**Issue by adelin-mcbsoft** [talisman-games/cordova-plugin-ui-sounds#1]
Hi,

First of all, thanks for the plugin - most probably the only one that satisfies my needs within cordova.

I've seen that currently the plugin can only load sounds stored locally (from the `www` folder).
However, under the development and testing environment, I have the cordova's source files loaded from a remote HTTP server, e.g.:

```
<platform name="android">
    	<content src="http://192.168.0.123:3000/android/www/index.html" />
    </platform>
    <platform name="ios">
        <content src="http://192.168.0.123:3000/ios/www/index.html" />
    </platform>
```

The thing is - the _cordova-plugin-ui-sounds_ does not care about the content source specified in config.xml, and tries to load the sounds directly from the `www` folder (no matter what), which does not contain the files under the development phase...

So my question is: is there any possibility to implement a way to preload/play files that are stored remotely?

Thanks,
A.

**Comment by andre-arsenault** [comment]
Hi, thanks for your question!

This was a deliberate choice I made during development of the plugin. There are other plugins that support loading assets from remote HTTP sources, but I needed something quick, fast, and local (fixed set of assets known ahead of time).

If I understand your use case correctly, adding HTTP loading would be a convenience during development but unnecessary during production.

I don't have any plans to update this plugin, as I no longer work in the Cordova ecosystem. If you would like to add this functionality on your own, I would recommend forking the repo and publishing it as a new plugin.

I'm happy the plugin has been helpful to you!
